### PR TITLE
[highcharts] Update build.boot

### PR DESCRIPTION
**Pull request by kenfehling**
I think this should be more in line with conventions

### CODE REVIEW

**Comment by gbuisson** [comment]
yeah, i just used jquery package as base template, yours looks better :+1:

**Comment by gbuisson** [comment]
why did you update c3 instead of highcharts ??

**Comment by kenfehling** [comment]
Ugh sorry, I was working on c3 too and I did the wrong one. I'll redo it.

**Comment by gbuisson** [comment]
i do it ;-)

**Pull request merged**
